// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF1sAmRDLEj5DHpQihI8ltA4Tr-Y_i15A',
    appId: '1:611002416338:web:7fd73f09eebe1e973f010b',
    messagingSenderId: '611002416338',
    projectId: 'fitcoachaz-519f3',
    authDomain: 'fitcoachaz-519f3.firebaseapp.com',
    storageBucket: 'fitcoachaz-519f3.appspot.com',
    measurementId: 'G-V3Q4VVEC1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnTJVqXBaRjHswOlwbhFQQWHhZaAciYyI',
    appId: '1:611002416338:android:fcdc1c9f881fb0513f010b',
    messagingSenderId: '611002416338',
    projectId: 'fitcoachaz-519f3',
    storageBucket: 'fitcoachaz-519f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuQZu7ToMtjdu4o1Ljcg6c2R70BbgpiCA',
    appId: '1:611002416338:ios:3a40bc7b6c12286d3f010b',
    messagingSenderId: '611002416338',
    projectId: 'fitcoachaz-519f3',
    storageBucket: 'fitcoachaz-519f3.appspot.com',
    androidClientId: '611002416338-pnr9ci1snh5ffs8vc3sj2ssauva7kb0n.apps.googleusercontent.com',
    iosClientId: '611002416338-dorsepe620766dpa627sabc6ftekh338.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitcoachaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuQZu7ToMtjdu4o1Ljcg6c2R70BbgpiCA',
    appId: '1:611002416338:ios:3a40bc7b6c12286d3f010b',
    messagingSenderId: '611002416338',
    projectId: 'fitcoachaz-519f3',
    storageBucket: 'fitcoachaz-519f3.appspot.com',
    androidClientId: '611002416338-pnr9ci1snh5ffs8vc3sj2ssauva7kb0n.apps.googleusercontent.com',
    iosClientId: '611002416338-dorsepe620766dpa627sabc6ftekh338.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitcoachaz',
  );
}
